// Generates test fixtures for moon_ycrdt from the official lib0 / Yjs
// implementations (versions pinned in scripts/package.json).
//
// Usage (from the repository root):
//   cd scripts && npm ci && node gen_fixtures.mjs
//
// Every fixture is written twice:
//   - fixtures/<name>.json     human-readable record of the data
//   - <pkg>/<name>_gen_test.mbt  the same data as MoonBit code, because the
//                                wasm-gc backend cannot read files in tests.

import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import * as encoding from 'lib0/encoding'
import * as Y from 'yjs'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const YJS_VERSION = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/node_modules/yjs/package.json'), 'utf8')).version
const LIB0_VERSION = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/node_modules/lib0/package.json'), 'utf8')).version

const HEADER = `// GENERATED by scripts/gen_fixtures.mjs from yjs@${YJS_VERSION} / lib0@${LIB0_VERSION}. DO NOT EDIT.\n`

export const hex = (u8) => Buffer.from(u8).toString('hex')

const enc = (f) => {
  const e = encoding.createEncoder()
  f(e)
  return hex(encoding.toUint8Array(e))
}

// ---------------------------------------------------------------------------
// MoonBit literal helpers

export const mbtString = (s) => {
  let out = '"'
  for (const ch of s) {
    const cp = ch.codePointAt(0)
    if (ch === '"') out += '\\"'
    else if (ch === '\\') out += '\\\\'
    else if (cp >= 0x20 && cp < 0x7f) out += ch
    else out += `\\u{${cp.toString(16)}}`
  }
  return out + '"'
}

const doubleBits = (d) => {
  const b = Buffer.alloc(8)
  b.writeDoubleBE(d)
  return '0x' + b.toString('hex') + 'UL'
}

const mbtAny = (v) => {
  const A = '@lib0.Any::'
  if (v === undefined) return A + 'Undefined'
  if (v === null) return A + 'Null'
  switch (typeof v) {
    case 'boolean': return `${A}Bool(${v})`
    case 'number': return `${A}Number((${doubleBits(v)}).reinterpret_as_double())`
    case 'bigint': return `${A}BigInt((0x${BigInt.asUintN(64, v).toString(16)}UL).reinterpret_as_int64())`
    case 'string': return `${A}String(${mbtString(v)})`
  }
  if (Array.isArray(v)) return `${A}Array([${v.map(mbtAny).join(', ')}])`
  if (v instanceof Uint8Array) return `${A}Bytes(b"${[...v].map(b => '\\x' + b.toString(16).padStart(2, '0')).join('')}")`
  return `${A}Object([${Object.keys(v).map(k => `(${mbtString(k)}, ${mbtAny(v[k])})`).join(', ')}])`
}

const writeFixture = (name, pkgDir, json, mbt) => {
  fs.mkdirSync(path.join(ROOT, 'fixtures'), { recursive: true })
  fs.writeFileSync(path.join(ROOT, 'fixtures', `${name}.json`), JSON.stringify(json, (k, v) => typeof v === 'bigint' ? v.toString() + 'n' : v, 2) + '\n')
  fs.writeFileSync(path.join(ROOT, pkgDir, `${name}_gen_test.mbt`), HEADER + mbt)
  console.log(`wrote fixtures/${name}.json and ${pkgDir}/${name}_gen_test.mbt`)
}

// ---------------------------------------------------------------------------
// lib0 encodings

const genLib0 = () => {
  const varUints = [0, 1, 2, 63, 64, 127, 128, 255, 256, 300, 16383, 16384, 2 ** 21 - 1, 2 ** 21,
    2 ** 31 - 1, 2 ** 31, 2 ** 32 - 1, 2 ** 32, 2 ** 53 - 1]
  const varInts = [0, 1, -1, 2, -2, 63, -63, 64, -64, 127, -127, 128, -128, 8191, -8191, 8192, -8192,
    2 ** 31 - 1, -(2 ** 31 - 1), 2 ** 31, -(2 ** 31), 2 ** 32, -(2 ** 32), 2 ** 53 - 1, -(2 ** 53 - 1)]
  const strings = ['', 'a', 'hello world', '中文', '你好，世界', '😀', 'a😀b', '👨‍👩‍👧', '\u0000', '﻿bom', 'é',
    'x'.repeat(200), '混合 mixed 😀 text']
  const byteArrays = [[], [0], [1, 2, 3], [255, 0, 128], Array.from({ length: 200 }, (_, i) => i & 0xff)]
  const anys = [
    undefined, null, true, false,
    0, -0, 1, -1, 42, 63, 64, -64, 127, 128, 2 ** 31 - 1, -(2 ** 31 - 1), 2 ** 31, -(2 ** 31), 2 ** 32, 2 ** 40, 2 ** 53 - 1,
    1.5, -2.25, 0.1, 3.14159, 1e300, -1e-300, Infinity, -Infinity, 16777217,
    10n, -1n, 2n ** 62n, -(2n ** 63n),
    '', 'str', '中文😀',
    [], [1, 'x', null], [[1, [2, [3]]], { a: [] }],
    {}, { a: 1 }, { key: 'value', n: 3.5, nested: { arr: [true, false, undefined], 中: '文' } },
    new Uint8Array([]), new Uint8Array([1, 2, 3])
  ]

  const json = {
    varUint: varUints.map(n => ({ value: n, hex: enc(e => encoding.writeVarUint(e, n)) })),
    varInt: varInts.map(n => ({ value: n, hex: enc(e => encoding.writeVarInt(e, n)) })),
    varString: strings.map(s => ({ value: s, hex: enc(e => encoding.writeVarString(e, s)) })),
    varUint8Array: byteArrays.map(a => ({ value: a, hex: enc(e => encoding.writeVarUint8Array(e, new Uint8Array(a))) })),
    any: anys.map(v => ({ value: v, hex: enc(e => encoding.writeAny(e, v)) })),
    // Lone surrogates cannot be represented portably in MoonBit literals; the
    // expected output is recorded here and checked through code units.
    loneSurrogate: { units: [0x61, 0xd83d, 0x62], hex: enc(e => encoding.writeVarString(e, 'a\ud83db')) }
  }

  let mbt = ''
  mbt += `\n///|\nlet var_uint_cases : Array[(UInt64, String)] = [\n${json.varUint.map(c => `  (${c.value}UL, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet var_int_cases : Array[(Int64, String)] = [\n${json.varInt.map(c => `  (${c.value}L, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet var_string_cases : Array[(String, String)] = [\n${json.varString.map(c => `  (${mbtString(c.value)}, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet var_bytes_cases : Array[(Array[Int], String)] = [\n${json.varUint8Array.map(c => `  ([${c.value.join(', ')}], "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet any_cases : Array[(@lib0.Any, String)] = [\n${json.any.map(c => `  (${mbtAny(c.value)}, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet lone_surrogate_case : (Array[Int], String) = ([${json.loneSurrogate.units.join(', ')}], "${json.loneSurrogate.hex}")\n`
  // JSON cannot hold undefined / -0 / Infinity faithfully, so store the Any list as hex + a description.
  json.any = json.any.map(c => ({ value: describe(c.value), hex: c.hex }))
  writeFixture('lib0', 'lib0', json, mbt)
}

const describe = (v) => {
  if (v === undefined) return 'undefined'
  if (Object.is(v, -0)) return '-0'
  if (typeof v === 'number' && !Number.isFinite(v)) return String(v)
  if (typeof v === 'bigint') return v.toString() + 'n'
  if (v instanceof Uint8Array) return { Uint8Array: [...v] }
  if (Array.isArray(v)) return v.map(describe)
  if (v !== null && typeof v === 'object') return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, describe(x)]))
  return v
}

// ---------------------------------------------------------------------------
// Update format v1

const newDoc = (clientID, opts = {}) => {
  const doc = new Y.Doc(opts)
  doc.clientID = clientID
  return doc
}

const idStr = (id) => id === null ? '-' : `${id.client}:${id.clock}`

// Canonical one-line description of a decoded struct; the MoonBit test builds
// the same string from its own decoder (update/update_test.mbt `describe`).
const describeStruct = (s) => {
  if (s instanceof Y.GC) return `GC ${idStr(s.id)} len=${s.length}`
  if (s instanceof Y.Skip) return `Skip ${idStr(s.id)} len=${s.length}`
  let parent = '-'
  if (typeof s.parent === 'string') parent = `root:${s.parent}`
  else if (s.parent instanceof Y.ID) parent = `item:${idStr(s.parent)}`
  return `Item ${idStr(s.id)} len=${s.length} o=${idStr(s.origin)} ro=${idStr(s.rightOrigin)} p=${parent} ps=${s.parentSub ?? '-'} ref=${s.content.getRef()}`
}

const describeDs = (ds) => [...ds.clients.entries()].map(([client, items]) =>
  `${client}:` + items.map(r => `[${r.clock},${r.len}]`).join('')).join(' ')

const updateScenarios = () => {
  const out = []
  const add = (name, update) => out.push({ name, update })

  {
    const d = newDoc(1)
    const t = d.getText('t')
    t.insert(0, 'ab'); t.insert(2, 'c'); t.delete(0, 1)
    add('text_basic_gc', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(1, { gc: false })
    const t = d.getText('t')
    t.insert(0, 'ab'); t.insert(2, 'c'); t.delete(0, 1)
    add('text_basic_nogc', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(7, { gc: false })
    const t = d.getText('text')
    t.insert(0, '你好😀世界'); t.insert(3, '🎉'); t.delete(3, 1) // splits a surrogate pair
    t.insert(0, 'é')
    add('text_unicode', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(3000000000) // client id above 2^31
    const m = d.getMap('m')
    m.set('int', 42); m.set('neg', -7); m.set('float', 1.5); m.set('double', 0.1)
    m.set('big', 2n ** 40n); m.set('str', '中文'); m.set('t', true); m.set('f', false); m.set('nil', null)
    m.set('arr', [1, 'two', [3]]); m.set('obj', { a: 1, b: { c: [null] } }); m.set('bin', new Uint8Array([1, 2, 3]))
    m.set('int', 43) // overwrite: origin present, parentSub bit set but key omitted
    m.delete('neg')
    add('map_values', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(5)
    const t = d.getText('rich')
    t.insert(0, 'hello world')
    t.format(0, 5, { bold: true })
    t.insertEmbed(5, { image: 'x.png' })
    t.insert(11, '!', { italic: true })
    add('text_format_embed', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(9)
    const arr = d.getArray('arr')
    const inner = new Y.Map()
    arr.insert(0, [inner, 'plain', 3])
    inner.set('k', 'v')
    const frag = d.getXmlFragment('xml')
    const el = new Y.XmlElement('p')
    el.setAttribute('class', 'c1')
    const txt = new Y.XmlText()
    frag.insert(0, [el, new Y.XmlHook('hook-name')])
    el.insert(0, [txt])
    txt.insert(0, 'xml text')
    const sub = new Y.Doc({ guid: 'sub-guid' })
    d.getMap('docs').set('sub', sub)
    add('nested_types', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(11) // gc: true turns children of deleted types into GC structs
    const arr = d.getArray('arr')
    const inner = new Y.Map()
    arr.insert(0, [inner, 'keep'])
    inner.set('a', 1); inner.set('b', 'two')
    arr.delete(0, 1)
    add('gc_structs', Y.encodeStateAsUpdate(d))
  }
  {
    const a = newDoc(1); const b = newDoc(2); const c = newDoc(3)
    a.getText('t').insert(0, 'base')
    Y.applyUpdate(b, Y.encodeStateAsUpdate(a)); Y.applyUpdate(c, Y.encodeStateAsUpdate(a))
    a.getText('t').insert(2, 'A'); b.getText('t').insert(2, 'B'); c.getText('t').insert(2, 'C')
    b.getText('t').delete(0, 1); c.getMap('m').set('x', 'y')
    Y.applyUpdate(a, Y.encodeStateAsUpdate(b)); Y.applyUpdate(a, Y.encodeStateAsUpdate(c))
    add('multi_client', Y.encodeStateAsUpdate(a))
  }
  {
    const d = newDoc(4)
    const t = d.getText('t')
    t.insert(0, 'hello')
    const sv = Y.encodeStateVector(d)
    t.insert(5, ' world')
    add('diff_from_sv', Y.encodeStateAsUpdate(d, sv))
    // A state vector that points into the middle of an item: written with an offset.
    const e = encoding.createEncoder()
    encoding.writeVarUint(e, 1); encoding.writeVarUint(e, 4); encoding.writeVarUint(e, 2)
    add('diff_mid_item', Y.encodeStateAsUpdate(d, encoding.toUint8Array(e)))
  }
  {
    const d = newDoc(6)
    const updates = []
    d.on('update', u => updates.push(u))
    const t = d.getText('t')
    t.insert(0, 'one'); t.insert(3, 'two'); t.insert(6, 'three')
    add('merged_with_skip', Y.mergeUpdates([updates[0], updates[2]]))
  }
  {
    // Legacy ContentJSON is never created by current Yjs, so craft it with lib0
    // and let Yjs normalise it: the fixture is what Yjs itself writes back.
    const e = encoding.createEncoder()
    encoding.writeVarUint(e, 1) // clients
    encoding.writeVarUint(e, 1); encoding.writeVarUint(e, 8); encoding.writeVarUint(e, 0)
    encoding.writeUint8(e, 2) // info: ContentJSON, no origins
    encoding.writeVarUint(e, 1); encoding.writeVarString(e, 'legacy')
    encoding.writeVarUint(e, 3)
    encoding.writeVarString(e, '{"a":1}'); encoding.writeVarString(e, '"s"'); encoding.writeVarString(e, 'undefined')
    encoding.writeVarUint(e, 0) // empty delete set
    const d = newDoc(100)
    Y.applyUpdate(d, encoding.toUint8Array(e))
    add('content_json', Y.encodeStateAsUpdate(d))
  }
  return out
}

const genUpdates = () => {
  const cases = updateScenarios().map(({ name, update }) => {
    const decoded = Y.decodeUpdate(update)
    return {
      name,
      update: hex(update),
      stateVector: hex(Y.encodeStateVectorFromUpdate(update)),
      structs: decoded.structs.map(describeStruct),
      deleteSet: describeDs(decoded.ds)
    }
  })
  let mbt = '\n///|\nlet update_cases : Array[(String, String, String, Array[String], String)] = [\n'
  for (const c of cases) {
    mbt += `  (\n    "${c.name}",\n    "${c.update}",\n    "${c.stateVector}",\n    [\n${c.structs.map(s => `      ${mbtString(s)},`).join('\n')}\n    ],\n    ${mbtString(c.deleteSet)},\n  ),\n`
  }
  mbt += ']\n'
  writeFixture('updates', 'update', cases, mbt)
}

// ---------------------------------------------------------------------------
// Yjs -> MoonBit interop: updates to apply in order, and what Yjs itself ends
// up with after applying them to a fresh (gc: false) document.

// Small deterministic PRNG so that fixtures are reproducible.
export const rng = (seed) => () => {
  seed |= 0; seed = seed + 0x6D2B79F5 | 0
  let t = Math.imul(seed ^ seed >>> 15, 1 | seed)
  t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t
  return ((t ^ t >>> 14) >>> 0) / 4294967296
}

export const RECEIVER_CLIENT = 999999

const recordUpdates = (doc) => {
  const updates = []
  doc.on('update', u => updates.push(u))
  return updates
}

const interopScenarios = () => {
  const out = []
  const add = (name, updates, texts = [], maps = []) => out.push({ name, updates, texts, maps })

  for (const { name, update } of updateScenarios()) {
    const texts = { text_basic_gc: ['t'], text_basic_nogc: ['t'], text_unicode: ['text'], text_format_embed: ['rich'], multi_client: ['t'], merged_with_skip: ['t'] }[name] ?? []
    const maps = { map_values: ['m'], multi_client: ['m'] }[name] ?? []
    add(`single_${name}`, [update], texts, maps)
  }
  {
    const d = newDoc(21, { gc: false })
    const ups = recordUpdates(d)
    const t = d.getText('t')
    t.insert(0, 'Hello, world')
    t.insert(5, ' there')
    t.delete(0, 1)
    t.insert(0, 'h')
    t.insert(t.length, ' 😀👍')
    t.delete(t.length - 3, 1) // inside the emoji pair -> U+FFFD halves
    t.insert(3, '中文')
    t.delete(2, 4)
    t.insert(2, 'XYZ')
    add('incremental_text', ups, ['t'])
  }
  {
    const d = newDoc(22)
    const ups = recordUpdates(d)
    const m = d.getMap('settings')
    m.set('theme', 'dark'); m.set('size', 12); m.set('ratio', 0.75)
    m.set('size', 14); m.delete('theme'); m.set('list', [1, 2, { x: null }])
    m.set('theme', 'light'); m.set('raw', new Uint8Array([9, 8, 7]))
    add('incremental_map', ups, [], ['settings'])
  }
  {
    // Three replicas, concurrent edits at the same positions, delivered to the
    // receiver shuffled and with duplicates (exercises the pending queue).
    const rand = rng(7)
    const docs = [newDoc(101), newDoc(202), newDoc(303)]
    const all = []
    docs.forEach(d => d.on('update', u => all.push(u)))
    docs[0].getText('t').insert(0, 'shared base')
    for (const d of docs.slice(1)) Y.applyUpdate(d, Y.encodeStateAsUpdate(docs[0]))
    docs[0].getText('t').insert(6, 'A1'); docs[1].getText('t').insert(6, 'B1'); docs[2].getText('t').insert(6, 'C1')
    docs[1].getText('t').delete(0, 3); docs[2].getText('t').delete(2, 5)
    docs[0].getMap('m').set('k', 'from0'); docs[2].getMap('m').set('k', 'from2'); docs[1].getMap('m').set('j', 1)
    Y.applyUpdate(docs[1], Y.encodeStateAsUpdate(docs[2]))
    docs[1].getText('t').insert(4, 'after-sync')
    docs[0].getText('t').insert(0, '>')
    const order = all.map((u, i) => [rand(), u]).sort((a, b) => a[0] - b[0]).map(x => x[1])
    order.splice(3, 0, order[0]); order.push(order[5])
    add('concurrent_shuffled', order, ['t'], ['m'])
  }
  return out
}

const genInterop = () => {
  const cases = interopScenarios().map(({ name, updates, texts, maps }) => {
    const r = newDoc(RECEIVER_CLIENT, { gc: false })
    for (const u of updates) Y.applyUpdate(r, u)
    return {
      name,
      updates: updates.map(hex),
      texts: texts.map(n => [n, r.getText(n).toString()]),
      maps: maps.map(n => {
        const m = r.getMap(n)
        return [n, [...m.keys()].sort().map(k => [k, m.get(k)])]
      }),
      stateVector: hex(Y.encodeStateVector(r)),
      state: hex(Y.encodeStateAsUpdate(r))
    }
  })
  let mbt = `\n///|\nlet receiver_client : UInt = ${RECEIVER_CLIENT}\n`
  mbt += '\n///|\nlet interop_cases : Array[InteropCase] = [\n'
  for (const c of cases) {
    mbt += '  {\n'
    mbt += `    name: "${c.name}",\n`
    mbt += `    updates: [\n${c.updates.map(u => `      "${u}",`).join('\n')}\n    ],\n`
    mbt += `    texts: [${c.texts.map(([n, s]) => `(${mbtString(n)}, ${mbtString(s)})`).join(', ')}],\n`
    mbt += `    maps: [${c.maps.map(([n, es]) => `(${mbtString(n)}, [${es.map(([k, v]) => `(${mbtString(k)}, ${mbtAny(v)})`).join(', ')}])`).join(', ')}],\n`
    mbt += `    state_vector: "${c.stateVector}",\n`
    mbt += `    state: "${c.state}",\n`
    mbt += '  },\n'
  }
  mbt += ']\n'
  const json = cases.map(c => ({ ...c, maps: c.maps.map(([n, es]) => [n, es.map(([k, v]) => [k, describe(v)])]) }))
  writeFixture('interop', 'tests', json, mbt)
}

// ---------------------------------------------------------------------------
// Concurrent convergence: random edits on 2-3 replicas at nearby positions,
// exchanged in random order with duplicates. Every step records the text Yjs
// has on the affected replica and the bytes of every local update.

const CHUNKS = ['a', 'b', 'xy', 'Z', '中', '文字', '😀', 'e😀', '👍z', ' ']

export const convergenceScenario = (seed) => {
  const rand = rng(seed * 7919 + 13)
  const pick = (arr) => arr[Math.floor(rand() * arr.length)]
  const n = 2 + Math.floor(rand() * 2)
  const ids = []
  while (ids.length < n) {
    const id = rand() < 0.5 ? 1 + Math.floor(rand() * 5) : Math.floor(rand() * 4294967295)
    if (!ids.includes(id)) ids.push(id)
  }
  const docs = ids.map(id => newDoc(id))
  const logs = docs.map(() => [])
  docs.forEach((d, i) => d.on('update', (u, _origin, _doc, tr) => { if (tr.local) logs[i].push(u) }))
  const ops = []
  const deliver = (from, to, indices) => {
    for (const i of indices) Y.applyUpdate(docs[to], logs[from][i])
    ops.push({ op: 'sync', from, to, indices, text: docs[to].getText('t').toString() })
  }
  const steps = 15 + Math.floor(rand() * 25)
  for (let s = 0; s < steps; s++) {
    const r = Math.floor(rand() * n)
    const t = docs[r].getText('t')
    const len = t.length
    const choice = rand()
    if (choice < 0.45 || len === 0) {
      const bias = rand()
      const pos = bias < 0.15 ? 0 : bias < 0.3 ? len : bias < 0.4 ? Math.floor(len / 2) : Math.floor(rand() * (len + 1))
      const text = pick(CHUNKS)
      const before = logs[r].length
      t.insert(pos, text)
      ops.push({ op: 'insert', replica: r, pos, str: text, update: logs[r].slice(before).map(hex), text: t.toString() })
    } else if (choice < 0.7) {
      const pos = Math.floor(rand() * len)
      const dl = 1 + Math.floor(rand() * Math.min(3, len - pos))
      const before = logs[r].length
      t.delete(pos, dl)
      ops.push({ op: 'delete', replica: r, pos, len: dl, update: logs[r].slice(before).map(hex), text: t.toString() })
    } else {
      const from = Math.floor(rand() * n)
      const to = (from + 1 + Math.floor(rand() * (n - 1))) % n
      if (logs[from].length === 0) continue
      const k = 1 + Math.floor(rand() * (logs[from].length + 1))
      const indices = Array.from({ length: k }, () => Math.floor(rand() * logs[from].length))
      deliver(from, to, indices)
    }
  }
  // final full exchange, in order
  for (let to = 0; to < n; to++) {
    for (let from = 0; from < n; from++) {
      if (from !== to && logs[from].length > 0) deliver(from, to, logs[from].map((_, i) => i))
    }
  }
  const finalText = docs[0].getText('t').toString()
  for (const d of docs) {
    if (d.getText('t').toString() !== finalText) throw new Error(`seed ${seed}: Yjs replicas did not converge`)
  }
  return { seed, clients: ids, ops, finalText }
}

const CONVERGENCE_CASES = 200

const genConvergence = () => {
  const cases = Array.from({ length: CONVERGENCE_CASES }, (_, i) => convergenceScenario(i + 1))
  const mbtOp = (o) => {
    switch (o.op) {
      case 'insert': return `Ins(${o.replica}, ${o.pos}, ${mbtString(o.str)}, [${o.update.map(u => `"${u}"`).join(', ')}], ${mbtString(o.text)})`
      case 'delete': return `Del(${o.replica}, ${o.pos}, ${o.len}, [${o.update.map(u => `"${u}"`).join(', ')}], ${mbtString(o.text)})`
      default: return `Sync(${o.from}, ${o.to}, [${o.indices.join(', ')}], ${mbtString(o.text)})`
    }
  }
  // One top-level definition per scenario keeps each text segment small.
  let mbt = ''
  for (const c of cases) {
    mbt += `\n///|\nlet convergence_case_${c.seed} : ConvergenceCase = {\n  seed: ${c.seed},\n  clients: [${c.clients.map(x => `${x}U`).join(', ')}],\n  ops: [\n`
    mbt += c.ops.map(o => `    ${mbtOp(o)},`).join('\n')
    mbt += `\n  ],\n  final_text: ${mbtString(c.finalText)},\n}\n`
  }
  mbt += `\n///|\nlet convergence_cases : Array[ConvergenceCase] = [\n${cases.map(c => `  convergence_case_${c.seed},`).join('\n')}\n]\n`
  writeFixture('convergence', 'tests', cases, mbt)
}

genLib0()
genUpdates()
genInterop()
genConvergence()
