// Generates test fixtures for moon_ycrdt from the official lib0 / Yjs
// implementations (versions pinned in scripts/package.json).
//
// Usage (from the repository root):
//   cd scripts && npm ci && node gen_fixtures.mjs
//
// Every fixture is written twice:
//   - fixtures/<name>.json     human-readable record of the data
//   - <pkg>/<name>_gen_test.mbt  the same data as MoonBit code, because the
//                                wasm-gc backend cannot read files in tests.

import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import * as encoding from 'lib0/encoding'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const YJS_VERSION = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/node_modules/yjs/package.json'), 'utf8')).version
const LIB0_VERSION = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/node_modules/lib0/package.json'), 'utf8')).version

const HEADER = `// GENERATED by scripts/gen_fixtures.mjs from yjs@${YJS_VERSION} / lib0@${LIB0_VERSION}. DO NOT EDIT.\n`

export const hex = (u8) => Buffer.from(u8).toString('hex')

const enc = (f) => {
  const e = encoding.createEncoder()
  f(e)
  return hex(encoding.toUint8Array(e))
}

// ---------------------------------------------------------------------------
// MoonBit literal helpers

export const mbtString = (s) => {
  let out = '"'
  for (const ch of s) {
    const cp = ch.codePointAt(0)
    if (ch === '"') out += '\\"'
    else if (ch === '\\') out += '\\\\'
    else if (cp >= 0x20 && cp < 0x7f) out += ch
    else out += `\\u{${cp.toString(16)}}`
  }
  return out + '"'
}

const doubleBits = (d) => {
  const b = Buffer.alloc(8)
  b.writeDoubleBE(d)
  return '0x' + b.toString('hex') + 'UL'
}

const mbtAny = (v) => {
  const A = '@lib0.Any::'
  if (v === undefined) return A + 'Undefined'
  if (v === null) return A + 'Null'
  switch (typeof v) {
    case 'boolean': return `${A}Bool(${v})`
    case 'number': return `${A}Number((${doubleBits(v)}).reinterpret_as_double())`
    case 'bigint': return `${A}BigInt((0x${BigInt.asUintN(64, v).toString(16)}UL).reinterpret_as_int64())`
    case 'string': return `${A}String(${mbtString(v)})`
  }
  if (Array.isArray(v)) return `${A}Array([${v.map(mbtAny).join(', ')}])`
  if (v instanceof Uint8Array) return `${A}Bytes(b"${[...v].map(b => '\\x' + b.toString(16).padStart(2, '0')).join('')}")`
  return `${A}Object([${Object.keys(v).map(k => `(${mbtString(k)}, ${mbtAny(v[k])})`).join(', ')}])`
}

const writeFixture = (name, pkgDir, json, mbt) => {
  fs.mkdirSync(path.join(ROOT, 'fixtures'), { recursive: true })
  fs.writeFileSync(path.join(ROOT, 'fixtures', `${name}.json`), JSON.stringify(json, (k, v) => typeof v === 'bigint' ? v.toString() + 'n' : v, 2) + '\n')
  fs.writeFileSync(path.join(ROOT, pkgDir, `${name}_gen_test.mbt`), HEADER + mbt)
  console.log(`wrote fixtures/${name}.json and ${pkgDir}/${name}_gen_test.mbt`)
}

// ---------------------------------------------------------------------------
// lib0 encodings

const genLib0 = () => {
  const varUints = [0, 1, 2, 63, 64, 127, 128, 255, 256, 300, 16383, 16384, 2 ** 21 - 1, 2 ** 21,
    2 ** 31 - 1, 2 ** 31, 2 ** 32 - 1, 2 ** 32, 2 ** 53 - 1]
  const varInts = [0, 1, -1, 2, -2, 63, -63, 64, -64, 127, -127, 128, -128, 8191, -8191, 8192, -8192,
    2 ** 31 - 1, -(2 ** 31 - 1), 2 ** 31, -(2 ** 31), 2 ** 32, -(2 ** 32), 2 ** 53 - 1, -(2 ** 53 - 1)]
  const strings = ['', 'a', 'hello world', '中文', '你好，世界', '😀', 'a😀b', '👨‍👩‍👧', '\u0000', '﻿bom', 'é',
    'x'.repeat(200), '混合 mixed 😀 text']
  const byteArrays = [[], [0], [1, 2, 3], [255, 0, 128], Array.from({ length: 200 }, (_, i) => i & 0xff)]
  const anys = [
    undefined, null, true, false,
    0, -0, 1, -1, 42, 63, 64, -64, 127, 128, 2 ** 31 - 1, -(2 ** 31 - 1), 2 ** 31, -(2 ** 31), 2 ** 32, 2 ** 40, 2 ** 53 - 1,
    1.5, -2.25, 0.1, 3.14159, 1e300, -1e-300, Infinity, -Infinity, 16777217,
    10n, -1n, 2n ** 62n, -(2n ** 63n),
    '', 'str', '中文😀',
    [], [1, 'x', null], [[1, [2, [3]]], { a: [] }],
    {}, { a: 1 }, { key: 'value', n: 3.5, nested: { arr: [true, false, undefined], 中: '文' } },
    new Uint8Array([]), new Uint8Array([1, 2, 3])
  ]

  const json = {
    varUint: varUints.map(n => ({ value: n, hex: enc(e => encoding.writeVarUint(e, n)) })),
    varInt: varInts.map(n => ({ value: n, hex: enc(e => encoding.writeVarInt(e, n)) })),
    varString: strings.map(s => ({ value: s, hex: enc(e => encoding.writeVarString(e, s)) })),
    varUint8Array: byteArrays.map(a => ({ value: a, hex: enc(e => encoding.writeVarUint8Array(e, new Uint8Array(a))) })),
    any: anys.map(v => ({ value: v, hex: enc(e => encoding.writeAny(e, v)) })),
    // Lone surrogates cannot be represented portably in MoonBit literals; the
    // expected output is recorded here and checked through code units.
    loneSurrogate: { units: [0x61, 0xd83d, 0x62], hex: enc(e => encoding.writeVarString(e, 'a\ud83db')) }
  }

  let mbt = ''
  mbt += `\n///|\nlet var_uint_cases : Array[(UInt64, String)] = [\n${json.varUint.map(c => `  (${c.value}UL, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet var_int_cases : Array[(Int64, String)] = [\n${json.varInt.map(c => `  (${c.value}L, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet var_string_cases : Array[(String, String)] = [\n${json.varString.map(c => `  (${mbtString(c.value)}, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet var_bytes_cases : Array[(Array[Int], String)] = [\n${json.varUint8Array.map(c => `  ([${c.value.join(', ')}], "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet any_cases : Array[(@lib0.Any, String)] = [\n${json.any.map(c => `  (${mbtAny(c.value)}, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet lone_surrogate_case : (Array[Int], String) = ([${json.loneSurrogate.units.join(', ')}], "${json.loneSurrogate.hex}")\n`
  // JSON cannot hold undefined / -0 / Infinity faithfully, so store the Any list as hex + a description.
  json.any = json.any.map(c => ({ value: describe(c.value), hex: c.hex }))
  writeFixture('lib0', 'lib0', json, mbt)
}

const describe = (v) => {
  if (v === undefined) return 'undefined'
  if (Object.is(v, -0)) return '-0'
  if (typeof v === 'number' && !Number.isFinite(v)) return String(v)
  if (typeof v === 'bigint') return v.toString() + 'n'
  if (v instanceof Uint8Array) return { Uint8Array: [...v] }
  if (Array.isArray(v)) return v.map(describe)
  if (v !== null && typeof v === 'object') return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, describe(x)]))
  return v
}

genLib0()
