// Generates test fixtures for moon_ycrdt from the official lib0 / Yjs
// implementations (versions pinned in scripts/package.json).
//
// Usage (from the repository root):
//   cd scripts && npm ci && node gen_fixtures.mjs
//
// Every fixture is written twice:
//   - fixtures/<name>.json     human-readable record of the data
//   - <pkg>/<name>_gen_test.mbt  the same data as MoonBit code, because the
//                                wasm-gc backend cannot read files in tests.

import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import * as encoding from 'lib0/encoding'
import * as Y from 'yjs'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const YJS_VERSION = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/node_modules/yjs/package.json'), 'utf8')).version
const LIB0_VERSION = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/node_modules/lib0/package.json'), 'utf8')).version

const HEADER = `// GENERATED by scripts/gen_fixtures.mjs from yjs@${YJS_VERSION} / lib0@${LIB0_VERSION}. DO NOT EDIT.\n`

export const hex = (u8) => Buffer.from(u8).toString('hex')

const enc = (f) => {
  const e = encoding.createEncoder()
  f(e)
  return hex(encoding.toUint8Array(e))
}

// ---------------------------------------------------------------------------
// MoonBit literal helpers

export const mbtString = (s) => {
  let out = '"'
  for (const ch of s) {
    const cp = ch.codePointAt(0)
    if (ch === '"') out += '\\"'
    else if (ch === '\\') out += '\\\\'
    else if (cp >= 0x20 && cp < 0x7f) out += ch
    else out += `\\u{${cp.toString(16)}}`
  }
  return out + '"'
}

const doubleBits = (d) => {
  const b = Buffer.alloc(8)
  b.writeDoubleBE(d)
  return '0x' + b.toString('hex') + 'UL'
}

const mbtAny = (v) => {
  const A = '@lib0.Any::'
  if (v === undefined) return A + 'Undefined'
  if (v === null) return A + 'Null'
  switch (typeof v) {
    case 'boolean': return `${A}Bool(${v})`
    case 'number': return `${A}Number((${doubleBits(v)}).reinterpret_as_double())`
    case 'bigint': return `${A}BigInt((0x${BigInt.asUintN(64, v).toString(16)}UL).reinterpret_as_int64())`
    case 'string': return `${A}String(${mbtString(v)})`
  }
  if (Array.isArray(v)) return `${A}Array([${v.map(mbtAny).join(', ')}])`
  if (v instanceof Uint8Array) return `${A}Bytes(b"${[...v].map(b => '\\x' + b.toString(16).padStart(2, '0')).join('')}")`
  return `${A}Object([${Object.keys(v).map(k => `(${mbtString(k)}, ${mbtAny(v[k])})`).join(', ')}])`
}

const writeFixture = (name, pkgDir, json, mbt) => {
  fs.mkdirSync(path.join(ROOT, 'fixtures'), { recursive: true })
  fs.writeFileSync(path.join(ROOT, 'fixtures', `${name}.json`), JSON.stringify(json, (k, v) => typeof v === 'bigint' ? v.toString() + 'n' : v, 2) + '\n')
  fs.writeFileSync(path.join(ROOT, pkgDir, `${name}_gen_test.mbt`), HEADER + mbt)
  console.log(`wrote fixtures/${name}.json and ${pkgDir}/${name}_gen_test.mbt`)
}

// ---------------------------------------------------------------------------
// lib0 encodings

const genLib0 = () => {
  const varUints = [0, 1, 2, 63, 64, 127, 128, 255, 256, 300, 16383, 16384, 2 ** 21 - 1, 2 ** 21,
    2 ** 31 - 1, 2 ** 31, 2 ** 32 - 1, 2 ** 32, 2 ** 53 - 1]
  const varInts = [0, 1, -1, 2, -2, 63, -63, 64, -64, 127, -127, 128, -128, 8191, -8191, 8192, -8192,
    2 ** 31 - 1, -(2 ** 31 - 1), 2 ** 31, -(2 ** 31), 2 ** 32, -(2 ** 32), 2 ** 53 - 1, -(2 ** 53 - 1)]
  const strings = ['', 'a', 'hello world', '中文', '你好，世界', '😀', 'a😀b', '👨‍👩‍👧', '\u0000', '﻿bom', 'é',
    'x'.repeat(200), '混合 mixed 😀 text']
  const byteArrays = [[], [0], [1, 2, 3], [255, 0, 128], Array.from({ length: 200 }, (_, i) => i & 0xff)]
  const anys = [
    undefined, null, true, false,
    0, -0, 1, -1, 42, 63, 64, -64, 127, 128, 2 ** 31 - 1, -(2 ** 31 - 1), 2 ** 31, -(2 ** 31), 2 ** 32, 2 ** 40, 2 ** 53 - 1,
    1.5, -2.25, 0.1, 3.14159, 1e300, -1e-300, Infinity, -Infinity, 16777217,
    10n, -1n, 2n ** 62n, -(2n ** 63n),
    '', 'str', '中文😀',
    [], [1, 'x', null], [[1, [2, [3]]], { a: [] }],
    {}, { a: 1 }, { key: 'value', n: 3.5, nested: { arr: [true, false, undefined], 中: '文' } },
    new Uint8Array([]), new Uint8Array([1, 2, 3])
  ]

  const json = {
    varUint: varUints.map(n => ({ value: n, hex: enc(e => encoding.writeVarUint(e, n)) })),
    varInt: varInts.map(n => ({ value: n, hex: enc(e => encoding.writeVarInt(e, n)) })),
    varString: strings.map(s => ({ value: s, hex: enc(e => encoding.writeVarString(e, s)) })),
    varUint8Array: byteArrays.map(a => ({ value: a, hex: enc(e => encoding.writeVarUint8Array(e, new Uint8Array(a))) })),
    any: anys.map(v => ({ value: v, hex: enc(e => encoding.writeAny(e, v)) })),
    // Lone surrogates cannot be represented portably in MoonBit literals; the
    // expected output is recorded here and checked through code units.
    loneSurrogate: { units: [0x61, 0xd83d, 0x62], hex: enc(e => encoding.writeVarString(e, 'a\ud83db')) }
  }

  let mbt = ''
  mbt += `\n///|\nlet var_uint_cases : Array[(UInt64, String)] = [\n${json.varUint.map(c => `  (${c.value}UL, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet var_int_cases : Array[(Int64, String)] = [\n${json.varInt.map(c => `  (${c.value}L, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet var_string_cases : Array[(String, String)] = [\n${json.varString.map(c => `  (${mbtString(c.value)}, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet var_bytes_cases : Array[(Array[Int], String)] = [\n${json.varUint8Array.map(c => `  ([${c.value.join(', ')}], "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet any_cases : Array[(@lib0.Any, String)] = [\n${json.any.map(c => `  (${mbtAny(c.value)}, "${c.hex}"),`).join('\n')}\n]\n`
  mbt += `\n///|\nlet lone_surrogate_case : (Array[Int], String) = ([${json.loneSurrogate.units.join(', ')}], "${json.loneSurrogate.hex}")\n`
  // JSON cannot hold undefined / -0 / Infinity faithfully, so store the Any list as hex + a description.
  json.any = json.any.map(c => ({ value: describe(c.value), hex: c.hex }))
  writeFixture('lib0', 'lib0', json, mbt)
}

const describe = (v) => {
  if (v === undefined) return 'undefined'
  if (Object.is(v, -0)) return '-0'
  if (typeof v === 'number' && !Number.isFinite(v)) return String(v)
  if (typeof v === 'bigint') return v.toString() + 'n'
  if (v instanceof Uint8Array) return { Uint8Array: [...v] }
  if (Array.isArray(v)) return v.map(describe)
  if (v !== null && typeof v === 'object') return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, describe(x)]))
  return v
}

// ---------------------------------------------------------------------------
// Update format v1

const newDoc = (clientID, opts = {}) => {
  const doc = new Y.Doc(opts)
  doc.clientID = clientID
  return doc
}

const idStr = (id) => id === null ? '-' : `${id.client}:${id.clock}`

// Canonical one-line description of a decoded struct; the MoonBit test builds
// the same string from its own decoder (update/update_test.mbt `describe`).
const describeStruct = (s) => {
  if (s instanceof Y.GC) return `GC ${idStr(s.id)} len=${s.length}`
  if (s instanceof Y.Skip) return `Skip ${idStr(s.id)} len=${s.length}`
  let parent = '-'
  if (typeof s.parent === 'string') parent = `root:${s.parent}`
  else if (s.parent instanceof Y.ID) parent = `item:${idStr(s.parent)}`
  return `Item ${idStr(s.id)} len=${s.length} o=${idStr(s.origin)} ro=${idStr(s.rightOrigin)} p=${parent} ps=${s.parentSub ?? '-'} ref=${s.content.getRef()}`
}

const describeDs = (ds) => [...ds.clients.entries()].map(([client, items]) =>
  `${client}:` + items.map(r => `[${r.clock},${r.len}]`).join('')).join(' ')

const updateScenarios = () => {
  const out = []
  const add = (name, update) => out.push({ name, update })

  {
    const d = newDoc(1)
    const t = d.getText('t')
    t.insert(0, 'ab'); t.insert(2, 'c'); t.delete(0, 1)
    add('text_basic_gc', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(1, { gc: false })
    const t = d.getText('t')
    t.insert(0, 'ab'); t.insert(2, 'c'); t.delete(0, 1)
    add('text_basic_nogc', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(7, { gc: false })
    const t = d.getText('text')
    t.insert(0, '你好😀世界'); t.insert(3, '🎉'); t.delete(3, 1) // splits a surrogate pair
    t.insert(0, 'é')
    add('text_unicode', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(3000000000) // client id above 2^31
    const m = d.getMap('m')
    m.set('int', 42); m.set('neg', -7); m.set('float', 1.5); m.set('double', 0.1)
    m.set('big', 2n ** 40n); m.set('str', '中文'); m.set('t', true); m.set('f', false); m.set('nil', null)
    m.set('arr', [1, 'two', [3]]); m.set('obj', { a: 1, b: { c: [null] } }); m.set('bin', new Uint8Array([1, 2, 3]))
    m.set('int', 43) // overwrite: origin present, parentSub bit set but key omitted
    m.delete('neg')
    add('map_values', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(5)
    const t = d.getText('rich')
    t.insert(0, 'hello world')
    t.format(0, 5, { bold: true })
    t.insertEmbed(5, { image: 'x.png' })
    t.insert(11, '!', { italic: true })
    add('text_format_embed', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(9)
    const arr = d.getArray('arr')
    const inner = new Y.Map()
    arr.insert(0, [inner, 'plain', 3])
    inner.set('k', 'v')
    const frag = d.getXmlFragment('xml')
    const el = new Y.XmlElement('p')
    el.setAttribute('class', 'c1')
    const txt = new Y.XmlText()
    frag.insert(0, [el, new Y.XmlHook('hook-name')])
    el.insert(0, [txt])
    txt.insert(0, 'xml text')
    const sub = new Y.Doc({ guid: 'sub-guid' })
    d.getMap('docs').set('sub', sub)
    add('nested_types', Y.encodeStateAsUpdate(d))
  }
  {
    const d = newDoc(11) // gc: true turns children of deleted types into GC structs
    const arr = d.getArray('arr')
    const inner = new Y.Map()
    arr.insert(0, [inner, 'keep'])
    inner.set('a', 1); inner.set('b', 'two')
    arr.delete(0, 1)
    add('gc_structs', Y.encodeStateAsUpdate(d))
  }
  {
    const a = newDoc(1); const b = newDoc(2); const c = newDoc(3)
    a.getText('t').insert(0, 'base')
    Y.applyUpdate(b, Y.encodeStateAsUpdate(a)); Y.applyUpdate(c, Y.encodeStateAsUpdate(a))
    a.getText('t').insert(2, 'A'); b.getText('t').insert(2, 'B'); c.getText('t').insert(2, 'C')
    b.getText('t').delete(0, 1); c.getMap('m').set('x', 'y')
    Y.applyUpdate(a, Y.encodeStateAsUpdate(b)); Y.applyUpdate(a, Y.encodeStateAsUpdate(c))
    add('multi_client', Y.encodeStateAsUpdate(a))
  }
  {
    const d = newDoc(4)
    const t = d.getText('t')
    t.insert(0, 'hello')
    const sv = Y.encodeStateVector(d)
    t.insert(5, ' world')
    add('diff_from_sv', Y.encodeStateAsUpdate(d, sv))
    // A state vector that points into the middle of an item: written with an offset.
    const e = encoding.createEncoder()
    encoding.writeVarUint(e, 1); encoding.writeVarUint(e, 4); encoding.writeVarUint(e, 2)
    add('diff_mid_item', Y.encodeStateAsUpdate(d, encoding.toUint8Array(e)))
  }
  {
    const d = newDoc(6)
    const updates = []
    d.on('update', u => updates.push(u))
    const t = d.getText('t')
    t.insert(0, 'one'); t.insert(3, 'two'); t.insert(6, 'three')
    add('merged_with_skip', Y.mergeUpdates([updates[0], updates[2]]))
  }
  {
    // Legacy ContentJSON is never created by current Yjs, so craft it with lib0
    // and let Yjs normalise it: the fixture is what Yjs itself writes back.
    const e = encoding.createEncoder()
    encoding.writeVarUint(e, 1) // clients
    encoding.writeVarUint(e, 1); encoding.writeVarUint(e, 8); encoding.writeVarUint(e, 0)
    encoding.writeUint8(e, 2) // info: ContentJSON, no origins
    encoding.writeVarUint(e, 1); encoding.writeVarString(e, 'legacy')
    encoding.writeVarUint(e, 3)
    encoding.writeVarString(e, '{"a":1}'); encoding.writeVarString(e, '"s"'); encoding.writeVarString(e, 'undefined')
    encoding.writeVarUint(e, 0) // empty delete set
    const d = newDoc(100)
    Y.applyUpdate(d, encoding.toUint8Array(e))
    add('content_json', Y.encodeStateAsUpdate(d))
  }
  return out
}

const genUpdates = () => {
  const cases = updateScenarios().map(({ name, update }) => {
    const decoded = Y.decodeUpdate(update)
    return {
      name,
      update: hex(update),
      stateVector: hex(Y.encodeStateVectorFromUpdate(update)),
      structs: decoded.structs.map(describeStruct),
      deleteSet: describeDs(decoded.ds)
    }
  })
  let mbt = '\n///|\nlet update_cases : Array[(String, String, String, Array[String], String)] = [\n'
  for (const c of cases) {
    mbt += `  (\n    "${c.name}",\n    "${c.update}",\n    "${c.stateVector}",\n    [\n${c.structs.map(s => `      ${mbtString(s)},`).join('\n')}\n    ],\n    ${mbtString(c.deleteSet)},\n  ),\n`
  }
  mbt += ']\n'
  writeFixture('updates', 'update', cases, mbt)
}

// ---------------------------------------------------------------------------
// Yjs -> MoonBit interop: updates to apply in order, and what Yjs itself ends
// up with after applying them to a fresh (gc: false) document.

// Small deterministic PRNG so that fixtures are reproducible.
export const rng = (seed) => () => {
  seed |= 0; seed = seed + 0x6D2B79F5 | 0
  let t = Math.imul(seed ^ seed >>> 15, 1 | seed)
  t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t
  return ((t ^ t >>> 14) >>> 0) / 4294967296
}

export const RECEIVER_CLIENT = 999999

const recordUpdates = (doc) => {
  const updates = []
  doc.on('update', u => updates.push(u))
  return updates
}

const interopScenarios = () => {
  const out = []
  const add = (name, updates, texts = [], maps = []) => out.push({ name, updates, texts, maps })

  for (const { name, update } of updateScenarios()) {
    const texts = { text_basic_gc: ['t'], text_basic_nogc: ['t'], text_unicode: ['text'], text_format_embed: ['rich'], multi_client: ['t'], merged_with_skip: ['t'] }[name] ?? []
    const maps = { map_values: ['m'], multi_client: ['m'] }[name] ?? []
    add(`single_${name}`, [update], texts, maps)
  }
  {
    const d = newDoc(21, { gc: false })
    const ups = recordUpdates(d)
    const t = d.getText('t')
    t.insert(0, 'Hello, world')
    t.insert(5, ' there')
    t.delete(0, 1)
    t.insert(0, 'h')
    t.insert(t.length, ' 😀👍')
    t.delete(t.length - 3, 1) // inside the emoji pair -> U+FFFD halves
    t.insert(3, '中文')
    t.delete(2, 4)
    t.insert(2, 'XYZ')
    add('incremental_text', ups, ['t'])
  }
  {
    const d = newDoc(22)
    const ups = recordUpdates(d)
    const m = d.getMap('settings')
    m.set('theme', 'dark'); m.set('size', 12); m.set('ratio', 0.75)
    m.set('size', 14); m.delete('theme'); m.set('list', [1, 2, { x: null }])
    m.set('theme', 'light'); m.set('raw', new Uint8Array([9, 8, 7]))
    add('incremental_map', ups, [], ['settings'])
  }
  {
    // Three replicas, concurrent edits at the same positions, delivered to the
    // receiver shuffled and with duplicates (exercises the pending queue).
    const rand = rng(7)
    const docs = [newDoc(101), newDoc(202), newDoc(303)]
    const all = []
    docs.forEach(d => d.on('update', u => all.push(u)))
    docs[0].getText('t').insert(0, 'shared base')
    for (const d of docs.slice(1)) Y.applyUpdate(d, Y.encodeStateAsUpdate(docs[0]))
    docs[0].getText('t').insert(6, 'A1'); docs[1].getText('t').insert(6, 'B1'); docs[2].getText('t').insert(6, 'C1')
    docs[1].getText('t').delete(0, 3); docs[2].getText('t').delete(2, 5)
    docs[0].getMap('m').set('k', 'from0'); docs[2].getMap('m').set('k', 'from2'); docs[1].getMap('m').set('j', 1)
    Y.applyUpdate(docs[1], Y.encodeStateAsUpdate(docs[2]))
    docs[1].getText('t').insert(4, 'after-sync')
    docs[0].getText('t').insert(0, '>')
    const order = all.map((u, i) => [rand(), u]).sort((a, b) => a[0] - b[0]).map(x => x[1])
    order.splice(3, 0, order[0]); order.push(order[5])
    add('concurrent_shuffled', order, ['t'], ['m'])
  }
  return out
}

const genInterop = () => {
  const cases = interopScenarios().map(({ name, updates, texts, maps }) => {
    const r = newDoc(RECEIVER_CLIENT, { gc: false })
    for (const u of updates) Y.applyUpdate(r, u)
    return {
      name,
      updates: updates.map(hex),
      texts: texts.map(n => [n, r.getText(n).toString()]),
      maps: maps.map(n => {
        const m = r.getMap(n)
        return [n, [...m.keys()].sort().map(k => [k, m.get(k)])]
      }),
      stateVector: hex(Y.encodeStateVector(r)),
      state: hex(Y.encodeStateAsUpdate(r))
    }
  })
  let mbt = `\n///|\nlet receiver_client : UInt = ${RECEIVER_CLIENT}\n`
  mbt += '\n///|\nlet interop_cases : Array[InteropCase] = [\n'
  for (const c of cases) {
    mbt += '  {\n'
    mbt += `    name: "${c.name}",\n`
    mbt += `    updates: [\n${c.updates.map(u => `      "${u}",`).join('\n')}\n    ],\n`
    mbt += `    texts: [${c.texts.map(([n, s]) => `(${mbtString(n)}, ${mbtString(s)})`).join(', ')}],\n`
    mbt += `    maps: [${c.maps.map(([n, es]) => `(${mbtString(n)}, [${es.map(([k, v]) => `(${mbtString(k)}, ${mbtAny(v)})`).join(', ')}])`).join(', ')}],\n`
    mbt += `    state_vector: "${c.stateVector}",\n`
    mbt += `    state: "${c.state}",\n`
    mbt += '  },\n'
  }
  mbt += ']\n'
  const json = cases.map(c => ({ ...c, maps: c.maps.map(([n, es]) => [n, es.map(([k, v]) => [k, describe(v)])]) }))
  writeFixture('interop', 'tests', json, mbt)
}

// ---------------------------------------------------------------------------
// Concurrent convergence: random edits on 2-3 replicas at nearby positions,
// exchanged in random order with duplicates. Every step records the text Yjs
// has on the affected replica and the bytes of every local update.

const CHUNKS = ['a', 'b', 'xy', 'Z', '中', '文字', '😀', 'e😀', '👍z', ' ']

// Map state as "key=value,..." sorted by key (MoonBit builds the same string).
export const mapState = (doc) => {
  const m = doc.getMap('m')
  return [...m.keys()].sort().map(k => `${k}=${m.get(k)}`).join(',')
}

export const CONVERGENCE_SEED_BASE = 7919

export const convergenceScenario = (seed) => {
  const rand = rng(seed * CONVERGENCE_SEED_BASE + 13)
  const pick = (arr) => arr[Math.floor(rand() * arr.length)]
  const n = 2 + Math.floor(rand() * 3)
  const ids = []
  while (ids.length < n) {
    const id = rand() < 0.5 ? 1 + Math.floor(rand() * 5) : Math.floor(rand() * 4294967295)
    if (!ids.includes(id)) ids.push(id)
  }
  const docs = ids.map(id => newDoc(id))
  const logs = docs.map(() => [])
  docs.forEach((d, i) => d.on('update', (u, _origin, _doc, tr) => { if (tr.local) logs[i].push(u) }))
  const ops = []
  const local = (r, op, f) => {
    const before = logs[r].length
    f()
    ops.push({ ...op, replica: r, update: logs[r].slice(before).map(hex), text: docs[r].getText('t').toString(), map: mapState(docs[r]) })
  }
  const deliver = (from, to, indices) => {
    for (const i of indices) Y.applyUpdate(docs[to], logs[from][i])
    ops.push({ op: 'sync', from, to, indices, text: docs[to].getText('t').toString(), map: mapState(docs[to]) })
  }
  const steps = 15 + Math.floor(rand() * 30)
  for (let s = 0; s < steps; s++) {
    const r = Math.floor(rand() * n)
    const t = docs[r].getText('t')
    const m = docs[r].getMap('m')
    const len = t.length
    const choice = rand()
    if (choice < 0.4 || len === 0) {
      const bias = rand()
      const pos = bias < 0.15 ? 0 : bias < 0.3 ? len : bias < 0.4 ? Math.floor(len / 2) : Math.floor(rand() * (len + 1))
      const str = pick(CHUNKS)
      local(r, { op: 'insert', pos, str }, () => t.insert(pos, str))
    } else if (choice < 0.6) {
      const pos = Math.floor(rand() * len)
      const dl = 1 + Math.floor(rand() * Math.min(3, len - pos))
      local(r, { op: 'delete', pos, len: dl }, () => t.delete(pos, dl))
    } else if (choice < 0.75) {
      // concurrent writes to a small set of keys
      const key = pick(['a', 'b', 'c'])
      if (m.has(key) && rand() < 0.3) {
        local(r, { op: 'mapDelete', key }, () => m.delete(key))
      } else {
        const value = Math.floor(rand() * 100)
        local(r, { op: 'mapSet', key, value }, () => m.set(key, value))
      }
    } else {
      const from = Math.floor(rand() * n)
      const to = (from + 1 + Math.floor(rand() * (n - 1))) % n
      if (logs[from].length === 0) continue
      const k = 1 + Math.floor(rand() * (logs[from].length + 1))
      const indices = Array.from({ length: k }, () => Math.floor(rand() * logs[from].length))
      deliver(from, to, indices)
    }
  }
  // final full exchange, in order
  for (let to = 0; to < n; to++) {
    for (let from = 0; from < n; from++) {
      if (from !== to && logs[from].length > 0) deliver(from, to, logs[from].map((_, i) => i))
    }
  }
  const finalText = docs[0].getText('t').toString()
  const finalMap = mapState(docs[0])
  for (const d of docs) {
    if (d.getText('t').toString() !== finalText || mapState(d) !== finalMap) throw new Error(`seed ${seed}: Yjs replicas did not converge`)
  }
  return { seed, clients: ids, ops, finalText, finalMap }
}

export const CONVERGENCE_CASES = 300

const mbtOp = (o) => {
  const ups = `[${(o.update ?? []).map(u => `"${u}"`).join(', ')}]`
  const after = `${mbtString(o.text)}, ${mbtString(o.map)}`
  switch (o.op) {
    case 'insert': return `Ins(${o.replica}, ${o.pos}, ${mbtString(o.str)}, ${ups}, ${after})`
    case 'delete': return `Del(${o.replica}, ${o.pos}, ${o.len}, ${ups}, ${after})`
    case 'mapSet': return `MSet(${o.replica}, ${mbtString(o.key)}, ${o.value}, ${ups}, ${after})`
    case 'mapDelete': return `MDel(${o.replica}, ${mbtString(o.key)}, ${ups}, ${after})`
    default: return `Sync(${o.from}, ${o.to}, [${o.indices.join(', ')}], ${after})`
  }
}

// Script cases as MoonBit code. Each case is built by its own function: a
// single initializer for all the data would exceed the wasm limit on the
// number of locals per function, and small segments format quickly.
const mbtScriptCases = (prefix, listName, cases) => {
  let mbt = ''
  cases.forEach((c, i) => {
    mbt += `\n///|\nfn ${prefix}_${i + 1}() -> ScriptCase {\n  {\n    name: ${mbtString(c.name)},\n    clients: [${c.clients.map(x => `${x}U`).join(', ')}],\n    ops: [\n`
    mbt += c.ops.map(o => `      ${mbtOp(o)},`).join('\n')
    mbt += `\n    ],\n    final_text: ${mbtString(c.finalText)},\n    final_map: ${mbtString(c.finalMap)},\n  }\n}\n`
  })
  mbt += `\n///|\nfn ${listName}() -> Array[ScriptCase] {\n  [\n${cases.map((_, i) => `    ${prefix}_${i + 1}(),`).join('\n')}\n  ]\n}\n`
  return mbt
}

const genConvergence = () => {
  const cases = Array.from({ length: CONVERGENCE_CASES }, (_, i) => convergenceScenario(i + 1))
    .map(c => ({ name: `seed ${c.seed}`, ...c }))
  writeFixture('convergence', 'tests', cases, mbtScriptCases('convergence_case', 'convergence_cases', cases))
}

// ---------------------------------------------------------------------------
// Edge cases in the same format: every UTF-16 position of a string with emoji,
// a ZWJ sequence and a combining mark (so inserts / deletes split surrogate
// pairs), empty inserts, deleting everything, extreme client ids.

const scriptRecorder = (name, ids) => {
  const docs = ids.map(id => newDoc(id))
  const logs = docs.map(() => [])
  docs.forEach((d, i) => d.on('update', (u, _o, _d, tr) => { if (tr.local) logs[i].push(u) }))
  const ops = []
  const text = (r) => docs[r].getText('t')
  const local = (r, op, f) => {
    const before = logs[r].length
    f()
    ops.push({ ...op, replica: r, update: logs[r].slice(before).map(hex), text: text(r).toString(), map: mapState(docs[r]) })
  }
  return {
    length: (r) => text(r).length,
    insert: (r, pos, str) => local(r, { op: 'insert', pos, str }, () => text(r).insert(pos, str)),
    del: (r, pos, len) => local(r, { op: 'delete', pos, len }, () => text(r).delete(pos, len)),
    syncAll: () => {
      for (let to = 0; to < docs.length; to++) {
        for (let from = 0; from < docs.length; from++) {
          if (from === to || logs[from].length === 0) continue
          const indices = logs[from].map((_, i) => i)
          for (const i of indices) Y.applyUpdate(docs[to], logs[from][i])
          ops.push({ op: 'sync', from, to, indices, text: text(to).toString(), map: mapState(docs[to]) })
        }
      }
    },
    finish: () => {
      const finalText = text(0).toString()
      for (let r = 0; r < docs.length; r++) {
        if (text(r).toString() !== finalText) throw new Error(`${name}: replicas differ`)
      }
      return { name, clients: ids, ops, finalText, finalMap: mapState(docs[0]) }
    }
  }
}

export const EDGE_STRING = 'a😀b👨‍👩‍👧ćd🎉'

const edgeScenarios = () => {
  const out = []
  const s = EDGE_STRING
  for (let p = 0; p <= s.length; p++) {
    const r = scriptRecorder(`insert at ${p}`, [10])
    r.insert(0, 0, s); r.insert(0, p, 'X'); r.insert(0, p, '😀')
    out.push(r.finish())
  }
  for (const len of [1, 2]) {
    for (let p = 0; p + len <= s.length; p++) {
      const r = scriptRecorder(`delete ${len} at ${p}`, [10])
      r.insert(0, 0, s); r.del(0, p, len)
      out.push(r.finish())
    }
  }
  {
    const r = scriptRecorder('empty insert, delete everything, write again', [10])
    r.insert(0, 0, ''); r.insert(0, 0, s); r.del(0, 0, s.length)
    r.insert(0, 0, '新'); r.del(0, 0, 1); r.insert(0, 0, '😀')
    out.push(r.finish())
  }
  {
    const r = scriptRecorder('typing at the end merges into one item', [10])
    for (const ch of ['h', 'e', 'l', 'l', 'o', '😀', '!']) r.insert(0, r.length(0), ch)
    out.push(r.finish())
  }
  {
    const r = scriptRecorder('client ids 0 and 2^32-1', [0, 4294967295])
    r.insert(0, 0, 'zero'); r.insert(1, 0, 'max'); r.syncAll()
    r.insert(0, 2, '|'); r.insert(1, 2, '|'); r.del(1, 0, 1); r.syncAll()
    out.push(r.finish())
  }
  {
    const r = scriptRecorder('two replicas split the same surrogate pair', [1, 2])
    r.insert(0, 0, 'x😀y'); r.syncAll()
    r.insert(0, 2, 'A'); r.insert(1, 2, 'B'); r.del(1, 1, 1); r.syncAll()
    r.del(0, 0, 1); r.insert(1, 0, '👍'); r.syncAll()
    out.push(r.finish())
  }
  return out
}

const genEdge = () => {
  const cases = edgeScenarios()
  const empty = new Y.Doc()
  const json = {
    emptyState: hex(Y.encodeStateAsUpdate(empty)),
    emptyStateVector: hex(Y.encodeStateVector(empty)),
    cases
  }
  let mbt = `\n///|\nlet empty_doc_state : String = "${json.emptyState}"\n\n///|\nlet empty_doc_state_vector : String = "${json.emptyStateVector}"\n`
  mbt += mbtScriptCases('edge_case', 'edge_cases', cases)
  writeFixture('edge', 'tests', json, mbt)
}

// ---------------------------------------------------------------------------
// Preservation of content moon_ycrdt does not model. Replica A (Yjs) creates
// the content; replica B loads it, edits the types it supports, then receives
// A's further edits *inside* the unsupported types. The expected values come
// from a Yjs replica with B's client id doing exactly the same.

const PRESERVE_B = 77

const preserveScenarios = () => {
  const out = []
  // build(a) creates the content on A; bOps run on B; later(a) edits on A again
  const add = (name, aClient, build, bOps, later) => out.push({ name, aClient, build, bOps, later })

  add('text formats and embeds', 5, a => {
    const t = a.getText('t')
    t.insert(0, 'hello world')
    t.format(0, 5, { bold: true })
    t.insertEmbed(5, { image: 'x.png' })
    t.insert(12, '!', { italic: true, color: '#f00' })
  }, [
    { op: 'insert', name: 't', pos: 2, str: '-B-' },
    { op: 'insert', name: 't', pos: 0, str: '😀' },
    { op: 'set', name: 'm', key: 'k', value: 'v' }
  ], a => {
    const t = a.getText('t')
    t.format(6, 3, { underline: true })
    t.insertEmbed(0, { video: 'y.mp4' })
  })

  add('xml elements, attributes, xml text and hooks', 6, a => {
    const frag = a.getXmlFragment('xml')
    const p = new Y.XmlElement('p')
    p.setAttribute('class', 'c1')
    const txt = new Y.XmlText()
    frag.insert(0, [p, new Y.XmlHook('my-hook')])
    p.insert(0, [txt])
    txt.insert(0, 'xml text')
  }, [
    { op: 'insert', name: 't', pos: 0, str: 'B text' },
    { op: 'set', name: 'm', key: 'n', value: 1 }
  ], a => {
    const frag = a.getXmlFragment('xml')
    const p = frag.get(0)
    p.setAttribute('id', 'x')
    p.removeAttribute('class')
    p.get(0).insert(3, ' more')
    frag.insert(1, [new Y.XmlElement('h1')])
  })

  add('arrays with any, binary and nested types', 7, a => {
    const arr = a.getArray('arr')
    const inner = new Y.Map()
    const innerText = new Y.Text()
    arr.insert(0, [1, 'two', new Uint8Array([3, 4]), inner, innerText, [5, { six: 6 }]])
    inner.set('k', 'v')
    innerText.insert(0, 'inner text')
  }, [
    { op: 'insert', name: 't', pos: 0, str: 'abc' },
    { op: 'delete', name: 't', pos: 1, len: 1 },
    { op: 'set', name: 'm', key: 'bytes', value: new Uint8Array([9]) }
  ], a => {
    const arr = a.getArray('arr')
    arr.insert(1, ['inserted'])
    arr.delete(0, 1)
    arr.get(3).set('k2', null)
    arr.get(4).insert(0, '>')
  })

  add('sub-documents', 8, a => {
    a.getMap('docs').set('sub', new Y.Doc({ guid: 'sub-guid' }))
  }, [
    { op: 'set', name: 'm', key: 'note', value: { nested: [true] } },
    { op: 'insert', name: 't', pos: 0, str: 'with subdoc' }
  ], a => {
    a.getMap('docs').set('sub2', new Y.Doc({ guid: 'sub-guid-2', meta: { a: 1 } }))
  })

  add('garbage-collected content from a gc document', 9, a => {
    const arr = a.getArray('arr')
    const inner = new Y.Map()
    arr.insert(0, [inner, 'keep'])
    inner.set('a', 1)
    arr.delete(0, 1) // inner map and its entries become GC / ContentDeleted
    const t = a.getText('t')
    t.insert(0, 'abcdef')
    t.delete(1, 3)
  }, [
    { op: 'insert', name: 't', pos: 1, str: 'B' },
    { op: 'delete', name: 't', pos: 0, len: 1 }
  ], a => {
    a.getText('t').insert(0, 'A')
    a.getArray('arr').insert(0, ['new'])
  })

  return out
}

const preserveCase = (sc) => {
  const a = newDoc(sc.aClient) // default gc: true
  const aUpdates = []
  a.on('update', u => aUpdates.push(u))
  sc.build(a)
  const base = Y.encodeStateAsUpdate(a)
  // reference replica for B
  const b = newDoc(PRESERVE_B, { gc: false })
  const bLocal = []
  b.on('update', (u, _o, _d, tr) => { if (tr.local) bLocal.push(u) })
  Y.applyUpdate(b, base)
  const opUpdates = []
  for (const o of sc.bOps) {
    const before = bLocal.length
    switch (o.op) {
      case 'insert': b.getText(o.name).insert(o.pos, o.str); break
      case 'delete': b.getText(o.name).delete(o.pos, o.len); break
      case 'set': b.getMap(o.name).set(o.key, o.value); break
    }
    opUpdates.push(bLocal.slice(before).map(hex))
  }
  const before = aUpdates.length
  sc.later(a)
  const later = aUpdates.slice(before)
  for (const u of later) Y.applyUpdate(b, u)
  // A also receives B's edits: both must agree on everything
  for (const u of bLocal) Y.applyUpdate(a, u)
  // compare the content of both replicas through typed getters on fresh docs
  const json = (d) => {
    const f = new Y.Doc()
    Y.applyUpdate(f, Y.encodeStateAsUpdate(d))
    const content = {
      t: f.getText('t').toDelta(),
      m: f.getMap('m').toJSON(),
      arr: f.getArray('arr').toJSON(),
      xml: f.getXmlFragment('xml').toString(),
      docs: [...f.getMap('docs').keys()].sort().map(k => f.getMap('docs').get(k).guid)
    }
    return JSON.stringify(content, (_k, v) => v instanceof Uint8Array ? [...v] : v)
  }
  if (json(a) !== json(b)) throw new Error(`${sc.name}: A and B differ`)
  return {
    name: sc.name,
    base: hex(base),
    ops: sc.bOps.map((o, i) => ({ ...o, update: opUpdates[i] })),
    later: later.map(hex),
    state: hex(Y.encodeStateAsUpdate(b)),
    text: b.getText('t').toString()
  }
}

const genPreserve = () => {
  const cases = preserveScenarios().map(preserveCase)
  const mbtPOp = (o) => {
    const ups = `[${o.update.map(u => `"${u}"`).join(', ')}]`
    switch (o.op) {
      case 'insert': return `TextIns(${mbtString(o.name)}, ${o.pos}, ${mbtString(o.str)}, ${ups})`
      case 'delete': return `TextDel(${mbtString(o.name)}, ${o.pos}, ${o.len}, ${ups})`
      default: return `MapSet(${mbtString(o.name)}, ${mbtString(o.key)}, ${mbtAny(o.value)}, ${ups})`
    }
  }
  let mbt = `\n///|\nlet preserve_client : UInt = ${PRESERVE_B}\n`
  cases.forEach((c, i) => {
    mbt += `\n///|\nlet preserve_case_${i + 1} : PreserveCase = {\n  name: ${mbtString(c.name)},\n  base: "${c.base}",\n  ops: [\n${c.ops.map(o => `    ${mbtPOp(o)},`).join('\n')}\n  ],\n  later: [${c.later.map(u => `"${u}"`).join(', ')}],\n  state: "${c.state}",\n  text: ${mbtString(c.text)},\n}\n`
  })
  mbt += `\n///|\nlet preserve_cases : Array[PreserveCase] = [${cases.map((_, i) => `preserve_case_${i + 1}`).join(', ')}]\n`
  const json = cases.map(c => ({ ...c, ops: c.ops.map(o => ({ ...o, value: o.value === undefined ? undefined : describe(o.value) })) }))
  writeFixture('preserve', 'tests', json, mbt)
}

// ---------------------------------------------------------------------------
// Yjs documents with content moon_ycrdt does not model (formats, embeds, XML,
// sub-documents), used by cmd/export to check that they survive MoonBit edits.

const genExportBase = () => {
  const byName = Object.fromEntries(updateScenarios().map(s => [s.name, hex(s.update)]))
  const json = { rich_text: byName.text_format_embed, nested_types: byName.nested_types }
  const mbt = `\n///|\nlet yjs_rich_text_update : String = "${json.rich_text}"\n\n///|\nlet yjs_nested_types_update : String = "${json.nested_types}"\n`
  fs.mkdirSync(path.join(ROOT, 'fixtures'), { recursive: true })
  fs.writeFileSync(path.join(ROOT, 'fixtures', 'export_base.json'), JSON.stringify(json, null, 2) + '\n')
  fs.writeFileSync(path.join(ROOT, 'cmd/export', 'yjs_base_gen.mbt'), HEADER + mbt)
  console.log('wrote fixtures/export_base.json and cmd/export/yjs_base_gen.mbt')
}

genLib0()
genUpdates()
genInterop()
genConvergence()
genEdge()
genPreserve()
genExportBase()
